// کلیدهای آیکون قابل انتخاب برای محصول و دسته‌بندی
// نگاشت SVG در فرانت‌اند (assets/icons.js) انجام می‌شود
module.exports = [
  { key: 'box',       fa: 'جعبه' },
  { key: 'art',       fa: 'تابلو' },
  { key: 'figure',    fa: 'فیگور' },
  { key: 'car',       fa: 'ماشین' },
  { key: 'plane',     fa: 'هواپیما' },
  { key: 'ship',      fa: 'کشتی' },
  { key: 'rocket',    fa: 'موشک' },
  { key: 'robot',     fa: 'ربات' },
  { key: 'gamepad',   fa: 'گیم' },
  { key: 'dice',      fa: 'بازی رومیزی' },
  { key: 'puzzle',    fa: 'پازل' },
  { key: 'lamp',      fa: 'لامپ و نور' },
  { key: 'neon',      fa: 'نئون' },
  { key: 'frame',     fa: 'قاب عکس' },
  { key: 'camera',    fa: 'دوربین' },
  { key: 'music',     fa: 'موسیقی' },
  { key: 'headphone', fa: 'هدفون' },
  { key: 'keyboard',  fa: 'کیبورد' },
  { key: 'mouse',     fa: 'ماوس' },
  { key: 'cpu',       fa: 'قطعات کامپیوتر' },
  { key: 'watch',     fa: 'ساعت' },
  { key: 'shirt',     fa: 'پوشاک' },
  { key: 'bag',       fa: 'کیف' },
  { key: 'cup',       fa: 'ماگ و لیوان' },
  { key: 'book',      fa: 'کتاب' },
  { key: 'pen',       fa: 'نوشت‌افزار' },
  { key: 'sticker',   fa: 'استیکر' },
  { key: 'card',      fa: 'کارت کلکسیونی' },
  { key: 'coin',      fa: 'سکه' },
  { key: 'medal',     fa: 'مدال' },
  { key: 'trophy',    fa: 'جام' },
  { key: 'crown',     fa: 'تاج' },
  { key: 'gem',       fa: 'جواهر' },
  { key: 'star',      fa: 'ستاره' },
  { key: 'heart',     fa: 'قلب' },
  { key: 'skull',     fa: 'اسکلت' },
  { key: 'ghost',     fa: 'روح' },
  { key: 'cat',       fa: 'گربه' },
  { key: 'dog',       fa: 'سگ' },
  { key: 'dragon',    fa: 'اژدها' },
  { key: 'tree',      fa: 'گیاه' },
  { key: 'flower',    fa: 'گل' },
  { key: 'globe',     fa: 'کره زمین' },
  { key: 'map',       fa: 'نقشه' },
  { key: 'anchor',    fa: 'لنگر' },
  { key: 'sword',     fa: 'شمشیر' },
  { key: 'shield',    fa: 'سپر' },
  { key: 'wand',      fa: 'جادو' },
  { key: 'palette',   fa: 'رنگ و نقاشی' },
  { key: 'sparkle',   fa: 'درخشش' }
];
